### ISSUE TITLE
Include view_with_own in master

### ISSUE THREAD

**Issue by madffm** [maxrossello/redmine_extended_watchers#13]
Hi,
is it possible to include the feature to only select users with rights from the branch to the master?
Does it work to overwrite extended_watchers_controller_patch.rb and extended_watchers_issue_patch.rb from the branch with the ones from master?
Maybe it is possible to have a switch in the settings of the plugin to switch this behavior on and off?
We really would like to use the plugin (with view_with_own) but we are afraid that the old branch has flaws which are fixed in the master.

Thanks
Matthias

**Comment by maxrossello** [comment]
Nice idea, unfortunately I am very short of time these days and I can only put this on the stack.

If you'd like to help, you may try to revert changes in commit https://github.com/maxrossello/redmine_extended_watchers/commit/57fc2e13ba0530d1d893d023a551b98d8a5cf0a7 using some fixed flag in if statements and test, then it will be easy to make the fixed flag become a plugin setting.

However, there are users reporting usage of the branched version with success

**Comment by DavidDolezalPPG** [comment]
Hi Max, still not time for add in master? It would be TOP, if it is possible to do it. It's exactly what I need for our Redmine. 

At the end... this version of master work good on 3.4.6 version. :-)

Thank for reply.

**Comment by maxrossello** [comment]
In my spare time, I am following a more disciplined way to craft robust plugins by testing them along with full Redmine tests (see redmine_testsuites). This way I hope to save time in the end.
I will keep in consideration your need and make this plugin the next to be added to the supported set.
However, consider that it will take some time!

**Comment by DavidDolezalPPG** [comment]
I understand you and thank you for your time and work. I would like to try to do it myself, but I don't understand where to start... :-( Plugin is TOP, I only need that watchers can work with issue like be a member of project. 

If I can help you with testing or something about it, let me know.

**Comment by maxrossello** [comment]
yeah, these are the steps that I will do:
* manually verify functionality on 3.4.13 and report any bug I need to be aware of
* add automated tests to cover the intended functionality
* add a configuration setting to enable the different behavior and import the behavior from branch
* add automated tests for the additions
* analyze and harvest enhancements from forks, based on 3.4
* add support to redmine_testsuites 3.4.x
* port to 4.0 and 4.1

Maybe you would be willing to cover the first point?

**Comment by maxrossello** [comment]
The plugin now explicitly supports Redmine 3.4.13 and allows to select default Redmine, protected (i.e. former 'with_view_own'), or extended watchers behavior from plugin settings.
A suite of automated tests will follow, however manual tests have been executed and redmine_testsuites make the Redmine tests pass when the plugin is installed.
Readme documentation should also be way clearer about intended behaviors.
Let me know if you find any issue. Thanks!
