### ISSUE TITLE
Problems with Extended Watchers plugin

### ISSUE THREAD

**Issue by quiquegalasso** [maxrossello/redmine_extended_watchers#20]
I already install the plugin, it shows me in the administration but does not display the options in the list "Visibility of requests".
I'm not found any errors in the instalation.
The configuration of Redmine is:

Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.0.0-p647 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  _query                         0.0.1
  redmine_extended_watchers      1.0.5

Can you help me with it?

**Comment by maxrossello** [comment]
I can't understand what you mean, sorry.

**Comment by quiquegalasso** [comment]
Ok. I try to explain the problem I have.
I´ve already install the Extended Watchers plugin but it doesn´t work as you describe.
When I install this plugin,  does not display the options I need to add any user in the system as a watcher of some issue.
I don´t know if the version of Redmine (3.1.1) we use is compatible with this plugin.
Do you understand the problem now?
Do you have any document to read about this plugin to understand more about it?
Thank you for the time.
Enrique

**Comment by maxrossello** [comment]
I haven't tried the most recent Redmine version yet, but this plugin does not change the user interface. It just extends the visibility scope of issues. Only effect on UI is that sometimes an invisible project becomes visible because of the user being added as a watcher to some of the project's issues.

**Comment by quiquegalasso** [comment]
Ok. I understand how it works, but the plugin doesn't work. 
We install the plugin like you descirbe in the notes, but believe mi that it doesn't work.
Redmine administration show it, like it was correctly installed, but not.
I need to activate it?
Excuse me for my bad english...

**Comment by maxrossello** [comment]
Fact is, I don't understand what you mean with "does not display the options I need to add any user in the system as a watcher of some issue". 
Do you mean that the "Add watcher" link disappears? Are you able to add watchers with the plugin not installed?

**Comment by maxrossello** [comment]
Maybe a couple of screenshots for with and without the plugin may help...

**Comment by maxrossello** [comment]
Closing for lagging a further response.
Plugin now explicitly supports Redmine 3.4.13 under a variety of watchers modified visibility behavior. Let me know if you experience further problems.
Thanks
