### ISSUE TITLE
Error 500 in Project issues view

### ISSUE THREAD

**Issue by matiporro** [maxrossello/redmine_extended_watchers#21]
Hi, how are you?

I installed the plugin and it seems to work as it should. But I have a problem with this:
“_If only watching an issue in a project, all other project modules will be hidden. The project overview is redirected to the issues view, showing just the watched issue(s)._”
 
I have a user, only watching an issue in a Project, lets call it “ProjectX”. 
At the Projects View, the user have a link to the project "ProjectX".
Other private Project modules are hidden for him in the Project view. But when clicking the “ProjectX”´s link Im not redirected to the issues view, but an error page:
 
_Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.
Back_
 
And in the log I get the following:
 
_Completed 500 Internal Server Error in 974ms (ActiveRecord: 234.3ms)
 
NoMethodError (undefined method 'sub' for #<Array:0x007f391cca0ee8>):
  app/controllers/issues_controller.rb:48:in 'index'
  lib/redmine/sudo_mode.rb:63:in 'sudo_mode'_

I'd appreciate if you could lend me a hand.

**Comment by maxrossello** [comment]
Other users seem to have experienced a similar problem. Now the plugin explicitly supports Redmine 3.4.13.
Let me know if you experience the same problem again.
Thanks
