### ISSUE TITLE
Redmine 4.0 support

### ISSUE THREAD

**Issue by LapshinIV** [maxrossello/redmine_extended_watchers#23]
Hello! unfortunately, the plugin doesn't support the new RM version (4.0.1)

for RM 3.4.6 works fine.

![redmine-error](https://user-images.githubusercontent.com/5661618/52345200-ff843b00-2a35-11e9-9406-f22d44143915.jpg)

Is there any further support for the plugin?

Thanks.

**Comment by maxrossello** [comment]
yes but it will not happen immediately, since a list of plugins needs to be ported in my spare time. Merge requests are very welcome. I do not see similar advancement from the forks as well

**Comment by tanertas** [comment]
Any news on this?

**Comment by maxrossello** [comment]
not yet sorry. Try to have a look at theirix fork, looks like he did the job

**Comment by ingjackperez2019** [comment]
This plugins does not compile for redmine 4.0. Thanks for the help

**Comment by maxrossello** [comment]
The plugin now explicitly supports Redmine 3.4.13 in a way that is probably compatible with 4.x as it does not make use of chained aliases any more.
Explicit support for 4.x will come later, however you can already try to give it a spin!

**Comment by tanertas** [comment]
This specific branch from this fork worked for me:
https://github.com/theirix/redmine_extended_watchers/tree/with_view_own

**Comment by maxrossello** [comment]
Plugin now supports Redmine 3.4, 4.0 and 4.1, on respective branches.

**Comment by tanertas** [comment]
@maxrossello thank you for work. I got this error on Redmine 4.0:
`Redmine::PluginRequirementError: redmine_extended_watchers plugin requires Redmine 4.1.1 or higher but current is 4.0.6.stable`

**Comment by maxrossello** [comment]
Hi, for Redmine 4.0 you should download from the dedicated branch https://github.com/maxrossello/redmine_extended_watchers/tree/4.0-extended_watchers. Master is aligned with Redmine 4.1.
Actually it does not change much, but when Redmine itself won't support 4.0 any more, similarly the plugin will remain idle (and stable) for that version.

**Comment by tanertas** [comment]
Thank you.
