### ISSUE TITLE
Got 500 error when watcher was not members

### ISSUE THREAD

**Issue by zuoliang365** [maxrossello/redmine_extended_watchers#25]
Hi, 
Thank your for the great plugin.
It works with Redmine 3.4.8.

My user got 500 error when click the project  name in "Projects" page, he was a watcher but not members of the project.(There are no error if he was a watcher and also a member of the project )

Would you please fix the bug, Thanks a lot!

**Comment by zuoliang365** [comment]
As long as it is not a member, whether it is public or private, there will be error 500.

**Comment by maxrossello** [comment]
Plugin updated to support Redmine 3.4.13
