### ISSUE TITLE
extended watchers on Redmine 4.2.0

### ISSUE THREAD

**Issue by ebergu** [maxrossello/redmine_extended_watchers#29]
First, thanks for this plugin :)

I can add non-member watcher when I am creating an issue , but I cannot add non-member watchers to a created issue
(works on 4.1.1)

(Roles » Non member: Issues visibility=Issues created by or assigned to the user)

Environment:
Redmine version 4.2.0.stable
Redmine plugins:
additionals 2.0.23
redmine_checklists 3.1.18
redmine_extended_watchers 4.1.1
redmine_smile_project_enumerations_custom_field_format 1.3.14

**Comment by maxrossello** [comment]
Hi, thanks for your report.

At the moment the set of plugins supported by https://github.com/maxrossello/redmine_testsuites does not pass the tests against Redmine 4.2.0 in full. I am working on it on my available time, which is not much '-).
Once they pass, I will also check that your use case is covered by this plugin's tests.

When all this would be done, branch 4.1-extended_watchers will be created and master would follow Redmine 4.2.0. A dedicated release will also be available.

Kind regards

**Comment by Thibaut69** [comment]
Hello Ebergu and Max,

I have exactly the same issue with redmine 4.2.0
I can't add watchers while editing an existing issue.

Hope you could fix this :)

Regards,

Thibaut

**Comment by Thibaut69** [comment]
Hi guys,

I've applied the patch allow_watchers_and_contributers_access_to_issues_4.1.0.patch linked to this issue :
https://www.redmine.org/issues/14318

And then update your code .rb file extended_watchers_issue_patch.rb to add in the case statement :  

when 'own_watch'
          !self.is_private?		
when 'own_watch_contributed'
          !self.is_private?	

It does the trick, you create a role "watcher", set the visibility as explained on : 
https://www.redmine.org/issues/14318

And you can add this role to a user or group on a public project.

**Comment by maxrossello** [comment]
Thanks @Thibaut69 for your effort.
I really hope to be able to finalize by the weekend.

Regarding the patch, I think that it is a different way of solving the problem which does not fit perfectly with this plugin's scope. I think this plugin and the patch fulfill slightly different needs. 

The patch leaves a project's manager to choose the visibility style; this comes at cost of interface cluttering and possible inconsistency of behavior from one project to the other, which may confuse the ordinary user.
The plugin pushes for a choice as a global behavior: choose a policy and enforce it consistently to the whole system.

The concept of "contributed" is interesting. I may consider it as an option for the future. However, I have gone through severe performance profiling recently, which was highly needed, and I am committed not to lose the results.

**Comment by Thibaut69** [comment]
Yes if you find a more elegant solution, it's better for everybody.

**Comment by maxrossello** [comment]
Just deployed version compatible with Redmine 4.2.0.

Problem was about RM supporting group watchers. The plugin extends the concept in similar way to user watchers. However, modification of a scope also in the Principal model was necessary.

Closing this issue, thanks to everybody. If any further problem, please open a dedicated issue. Thanks.
