### ISSUE TITLE
Can send issue's note?

### ISSUE THREAD

**Issue by DolezalDavid** [maxrossello/redmine_extended_watchers#31]
Hi, 
I just tested your great plugin on 4.2.1 and it works perfect. Will be possible to add function/patch for Extended setup, that watcher can add/sent issue's note for existing issue? 

Here is example:
I'm boss and I have teams. Each team has own private project. But for one issue I need support from guy, who hasn't access to the project, because he's from another team.

1) Yes, I can give him access as member with tasks visibility: tasks created/assigned to the user. But his not author or assignee = WRONG
2) Yes, I can give him access as member with tasks visibility: all non-private tasks. But he will see all task in project = WRONG

Your plugin is perfect solution for this situation. He will see only task, where he's watcher (never will be assignee or author), but he needs to add note... 

Is it possible? 

Feel free for questions. 

Thank you for your help.

**Comment by maxrossello** [comment]
Sounds like a reasonable idea. However, one could argue that all of the issue tracking permissions (e.g. add further watchers, manage issue relations, etc.) should be available as an option, which means using a full role for the scope.

I think that you can achieve your scope by using the protected mode. Try the following:
1. switch the plugin to Protected mode
2. create a new role, e.g. "Watcher", with issue visibility "created or assigned to the user". This will prevent any user in the role to view anything by default, except for the project existence
2. setup the issue visibility permissions you like. For example, edit issue, add watchers, etc.
3. add any user to the role. You will be able to add the user as a watcher and gain the defined permissions much like Redmine allows when assigning the issue

While I was testing these instructions, I realized that in protected mode, by adding groups of users as members (e.g. to speedup configuration) the add watchers dialog does not popup. So stick to individual users for the moment. I will track this on a separate bug issue.

Let me know if this works for you. Thanks!

**Comment by DolezalDavid** [comment]
Hi @maxrossello ,
Thank you again. I just finished tests and it works good. Except the issue which you described before 10 days. ;-) Good job!
