### ISSUE TITLE
redmine_extended_watchers (4.2.2) to group users (redmine 4.2.3)

### ISSUE THREAD

**Issue by ebergu78** [maxrossello/redmine_extended_watchers#35]
Hola!
Gracias por resolver el pedido #30 
Actualicé las versiones de Redmine y el plugin y luego de la prueba observo que:
En modo extendido, al agregar un grupo de miembros como observadores, el grupo agregado no aparece en el listado de seguidores ( el grupo se agrega efectivamente como Seguidor pero la pantalla debe refrescarse)
Por otro lado, cuando ejecuto una consulta de peticiones con filtro: 'Watcher is me': no lista la petición en la que soy seguidor mediante un grupo.
Muchas gracias

**Comment by maxrossello** [comment]
`Por otro lado, cuando ejecuto una consulta de peticiones con filtro: 'Watcher is me': no lista la petición en la que soy seguidor mediante un grupo.`

This is default behavior of Redmine. Being watcher through a group membership does not mean to be watcher as an individual too, and the filter is managed by Redmine according to this logic. Btw this was also the main difficulty to make a group watch to disclose further permissions without creating a regression to Redmine in all other respects. If you remove the plugin, plain Redmine will behave like that.

For the other part of the issue, I will try to reproduce the issue asap. Probably an automated test is missing for the scenario.

**Comment by maxrossello** [comment]
Issue solved in version 4.2.3.
Root cause was a nasty missed update of watcher's relation eager loading on watched issue.
