### ISSUE TITLE
Missing template, responding with 404: Missing partial settings/_extwatch_settings

### ISSUE THREAD

**Issue by inittab** [maxrossello/redmine_extended_watchers#37]
Hi. I just cloned redmine_extended_watchers in my Redmine (4.0.4) plugins directory, but when I try to configure it from the Plugins administration I get a 404 with this log:
`
Started GET "/settings/plugin/redmine_extended_watchers" for X.X.X.X at 2021-12-05 19:58:15 +0100
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_extended_watchers"}
  Current user: foobar (id=3)
  Rendering settings/plugin.html.erb within layouts/admin
  Rendered settings/plugin.html.erb within layouts/admin (2.2ms)
Missing template, responding with 404: Missing partial settings/_extwatch_settings with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
  * "/usr/share/redmine/app/views"

  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 25ms (Views: 12.3ms | ActiveRecord: 2.9ms)
`
I have tried with commit c7571532cba00793dd566c73d1787cf2aab443b6 (branch 4.0-extended_watchers) and e9efa68054f32ffa87f41ead4efe95fc48278d37 (tag extended_watchers-4.0.0), both with same result.

The first time I restarted redmine, the checked out code was from master, and didn't work at all. Don't know if that could have left something pending/broken in the DB...

**Comment by maxrossello** [comment]
The file for the partial is there: https://github.com/maxrossello/redmine_extended_watchers/blob/4.0-extended_watchers/app/views/settings/_extwatch_settings.html.erb

Maybe you have wrong file permissions. In any case you should at least upgrade to latest Redmine version for 4.0 branch, i.e. 4.0.9 (which in any case is now frozen).

Also, try to investigate on possible incompatibility with other plugins.

**Comment by ebergu** [comment]
hola! 
con la versión redmine 4.2.3 + watchers 4.2.2, también muestra error 404 al intentar configurar cualquier plugins desde el módulo de Administración

**Comment by maxrossello** [comment]
@ebergu since this latest version is well tested and also reported working for other users, go through analysis of your own installation:

1. check that files are extracted with proper file permissions
2. try to remove every other plugin first, then incrementally try add one third party plugin at a time

Does your 404 error complain against the same file?
Also, for the sake of other people, better to use english as a standard language, thanks

**Comment by maxrossello** [comment]
Closing the issue for being idle. Feel free to reopen. Thanks.
