### ISSUE TITLE
Bitnami 4.1.0.8

### ISSUE THREAD

**Issue by konpega** [maxrossello/redmine_extended_watchers#46]
Hi
I tried both master, 4.1 and 4.0 branches for Bitnami 4.1.0.8. But none of them is working. 
In installation it is written simply install and restart, but this is not also working. After copying the code to plugin folder
it is working after migration. Master and 4.1 version during the migration gives warning (4.1 version is available ony in 4.1.1 your system 4.1.0). 4.0 is not warning but is not working.

**Comment by maxrossello** [comment]
Hi,
I believe it's not even possible to download a Bitnami Redmine version that's that old. Even official Redmine 4.1 branch is not maintained anymore. So, is there a particular reason to stick with old and unmaintained software?

If you still want to use this plugin over Redmine 4.1.0, you may try to remove or modify the 'requires_redmine' statement in init.rb. The reason why this plugin does not have a 4.1.0 version is that Redmine 4.1.1 was already out when the plugin was ported to 4.1. It _should_ work with 4.1.0 as well, but it is not tested.

However, my suggestion is to update to a more recent version of Redmine in first instance, at least 4.2. If some of the plugins you are using cannot be updated, then you should seriously think whether is a good thing to stick on them.

**Comment by konpega** [comment]
Hi,
Thanks for your all comments, I appreciate. 
It is true that some plugins used in the configuration work with this version.
The other one is the database version. When I try to install a new version I could not transfer the sql data with the same format to the new version one year ago. 
Maybe it is time to try one more time with later one.
For the other suggestion (init.rb) will try. 
Thanks
