### ISSUE TITLE
Sync releases with redmine plugins page

### ISSUE THREAD

**Issue by aseques** [maxrossello/redmine_extended_watchers#47]
I am using this plugin with current versions without any issues (and it's great), it's a pitty that the version mentioned in the plugins directory [here](https://www.redmine.org/plugins/redmine_extended_watchers) is listing compatiblity only with version 2.x of redmine and the plugin is stuck on 0.0.3.
Could you refresh the status there? I could investigate it but probably only the owner of the plugin can make the needed changes.

Regards

**Comment by maxrossello** [comment]
you are right!
Note taken

**Comment by maxrossello** [comment]
Done!
