### ISSUE TITLE
Redmine version 4.2.10 support

### ISSUE THREAD

**Issue by kolianik** [maxrossello/redmine_extended_watchers#48]
When I try to install the plugin for redmine 4.2.10, redmine refuses to start, please tell me what could be causing this, I checked the plugin in the following versions: 4.2.0, 4.2.1, 4.2.2, 4.2.3, 5.0.2, Immediately after installing and restarting the redmine server, the process crashes.

**Comment by maxrossello** [comment]
You can use version 4.2.3, but without a further hint I really can't help you. 

Make sure you have a first run isolated from other plugins (i.e. delete all the others), then add back the others one by one in order to detect which one may be in conflict.

**Comment by kolianik** [comment]
It turned out that the problem was not with the plugin, sorry to bother you. I didn’t look at the logs carefully, redmine didn’t like the name of the folder in the path to the plugin, and wrote about it in the logs.
