### ISSUE TITLE
Not working after Update to redmine 5.0.10

### ISSUE THREAD

**Issue by smap9** [maxrossello/redmine_extended_watchers#56]
Hello,

the plugin is not working after updating redmine to 5.0.10. In the News of the version is written "These releases include an important change to watcher permissions. The watchers list in the sidebar is now available only to users with the "View watchers list" permission. Previously, users with just the "Add watchers" permission could see the list, which was a potential data leak."

I can search for watchers but I'm not able to add them. No error is shown or in the logfile.

After a downgrade to redmine 5.0.9 it is working well again.

Maybe the [changes](https://www.redmine.org/projects/redmine/repository/svn/revisions/23168/diff) have to be made in this plugin, too.

Thanks for your support

**Comment by maxrossello** [comment]
I can confirm your understanding. The plugin needs an adaptation which I have in progress. I will deliver changes for 5.0.10 together with those for 5.1.4, then I will approach the compatibility with 6.0.0.

In general a redmine version can be considered covered by a plugin version iff a proper testsuites-x.y.z tag had been delivered in [redmine_testsuites](https://github.com/maxrossello/redmine_testsuites/tags) and that tag declares its compatibility. Currently only [5.0.9](https://github.com/maxrossello/redmine_testsuites/releases/tag/testsuites-5.0.9) is available.

Unfortunately I work on this in my spare time, so I am always a bit late wrt the official Redmine releases.
