### ISSUE TITLE
Redmine 6 Compatibility

### ISSUE THREAD

**Issue by tuzumkuru** [maxrossello/redmine_extended_watchers#57]
First of all thanks for this great plugin. It helps a lot. It is very helpful to give view permission to some users just by adding as a watcher. 

I am thinking of upgrading to Redmine V6, so testing the compatibility of plugins. 

The plugin installs with no problems but the functionality does not work. 

Do you have any plans to make it work in Redmine V6?

**Comment by maxrossello** [comment]
I will deliver updates for 5.0.10 and 5.1.4 shortly. Supporting a new release like 6.0.1 requires more time but I'm working on it in my spare time

**Comment by maxrossello** [comment]
Version 6.0.1 is now available

**Comment by tuzumkuru** [comment]
Thank you very much.
