### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by atopcu** [maxrossello/redmine_extended_watchers#6]
Hi,
This plugin function is importand for our redmine instance. However, each click take  2 seconds normally, but this time is 8 seconds when this plugin activated.
Is there any way to decrease this time?

Environment:
  Redmine version                2.3.3.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  author                         0.1.0
  autowatch                      0.1.0
  due_date_reminder              0.3.2
  extended_fields                0.2.2
  periodictask                   2.0.0
  redmine_assets_plugin          0.0.1
  redmine_banner                 0.0.9
  redmine_category_tree          0.0.3
  redmine_changeauthor           1.0.0
  redmine_contacts               3.2.5-pro
  redmine_contacts_helpdesk      2.2.5-pro
  redmine_dmsf                   1.4.6 stable
  redmine_extended_watchers      0.0.4
  redmine_favourite_projects     0.6.3
  redmine_gemavatar              1.0.3
  redmine_ics_export             2.0.0.dev
  redmine_information            1.0.2
  redmine_inline_attach_screenshot 0.4.6
  redmine_inline_note_images_plugin 0.0.1
  redmine_issue_checklist        2.0.5
  redmine_ldap_sync              2.0.2
  redmine_login_audit            0.1.1
  redmine_logs                   0.0.5
  redmine_reorder_links_arbitrary 0.0.7
  redmine_stealth                0.6.0
  redmine_textilizable_custom_fields 0.0.1
  redmine_theme_changer          0.1.0
  redmine_wiki_extensions        0.6.4
  role_shift                     0.1.0b
  sidebar_hide                   0.0.4
  under_construction             0.0.1
  wiking                         0.0.4

Best Regards,
Adnan

**Comment by maiconzucco** [comment]
Hi,

I tried the alteration above.

In the file lib/extended_watchers_issue_patch.rb a replaced:
#watched_group_issues_clause <<  " OR #{table_name}.id IN (#{watched_issues.join(',')})" <<
        watched_group_issues_clause <<  " OR #{table_name}.id IN ( select watchable_id from watchers where watchable_type = 'Issue' and user_id = #{user.id} )" <<

For me works fine and improve the page load speed.

**Comment by maxrossello** [comment]
The plugin has now a refreshed architecture. Closing this very important issue as obsoleted. In case a problem still holds, please open a new issue based on Redmine 3.4 or later (support for 4.x is coming soon). Thanks everybody for your effort and collaboration!
